### ISSUE TITLE
It shows error 'TypeError: Cannot read properties of undefined (reading 'defaultProps')' when use Layout in awesome_tshirt 

### ISSUE THREAD

**Issue by shenhuiqi** [odoo/tutorials#13]
I run tutorials awesome_tshirt (branch 16.0) in odoo 16, according to the 'Chapter 2: Odoo Web Framework' add Layout in dashboard component.

dashboard.js
`/** @odoo-module **/

import { Component } from "@odoo/owl";
import { registry } from "@web/core/registry";
import { Layout } from "@web/search/layout";

class AwesomeDashboard extends Component {
    setup(){
        this.display = {
            controlPanel: { "top-right": false, "bottom-right": false },
        };
    }
}

AwesomeDashboard.components = { Layout };
AwesomeDashboard.template = "awesome_tshirt.clientaction";

registry.category("lazy_components").add("AwesomeDashboard", AwesomeDashboard);
`
dashboard.xml
`<?xml version="1.0" encoding="UTF-8" ?>
<templates xml:space="preserve">

    <t t-name="awesome_tshirt.clientaction" owl="1">
        <Layout display="display">
            Hello
        </Layout>
    </t>

</templates>
`

After activated in Odoo Apps, it showed the error like below:
`UncaughtPromiseError > OwlError
Uncaught Promise > An error occured in the owl lifecycle (see this Error's "cause" property)
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (http://127.0.0.1:8069/web/assets/debug/web.assets_common.js:16294:35) (/web/static/lib/owl/owl.js:124)
    at owl.App.handleError (http://127.0.0.1:8069/web/assets/debug/web.assets_common.js:21846:20) (/web/static/lib/owl/owl.js:5676)
    at Fiber._render (http://127.0.0.1:8069/web/assets/debug/web.assets_common.js:17794:30) (/web/static/lib/owl/owl.js:1624)
    at Fiber.render (http://127.0.0.1:8069/web/assets/debug/web.assets_common.js:17783:18) (/web/static/lib/owl/owl.js:1613)
    at ComponentNode.initiateRender (http://127.0.0.1:8069/web/assets/debug/web.assets_common.js:18509:23) (/web/static/lib/owl/owl.js:2339)

Caused by: TypeError: Cannot read properties of undefined (reading 'defaultProps')
    at new ComponentNode (http://127.0.0.1:8069/web/assets/debug/web.assets_common.js:18472:36) (/web/static/lib/owl/owl.js:2302)
    at http://127.0.0.1:8069/web/assets/debug/web.assets_common.js:21837:28 (/web/static/lib/owl/owl.js:5667)
    at Layout.template (eval at compile (http://127.0.0.1:8069/web/assets/debug/web.assets_common.js:21612:16), <anonymous>:29:27) (/web/static/lib/owl/owl.js:5442)
    at Fiber._render (http://127.0.0.1:8069/web/assets/debug/web.assets_common.js:17791:38) (/web/static/lib/owl/owl.js:1621)
    at Fiber.render (http://127.0.0.1:8069/web/assets/debug/web.assets_common.js:17783:18) (/web/static/lib/owl/owl.js:1613)
    at ComponentNode.initiateRender (http://127.0.0.1:8069/web/assets/debug/web.assets_common.js:18509:23) (/web/static/lib/owl/owl.js:2339)
	
	TypeError: Cannot read properties of undefined (reading 'defaultProps')`

**Comment by AntoineVDV** [comment]
@fdardenne I believe this is for you :D

**Comment by fdardenne** [comment]
Hello,

In V16 the `Layout` component API requires some options to be passed with `useSubEnv`. 
This environment API is no more required > v16.

You see in the v16 solution how it can be done.
https://github.com/odoo/tutorials/commit/c1803a7ef4e19372f39951e99a626a3047825eed

**Comment by maramzeyad** [comment]
UncaughtPromiseError > OwlError
Uncaught Promise > The following error occurred in onWillStart: "Cannot set properties of undefined (setting 'domain')"
OwlError: The following error occurred in onWillStart: "Cannot set properties of undefined (setting 'domain')"
    at wrapError (https://colorado-qc.odoo.com/web/assets/3d8db59/web.assets_web.min.js:1044:77)
    at onWillStart (https://colorado-qc.odoo.com/web/assets/3d8db59/web.assets_web.min.js:1050:117)
    at WithSearch.setup (https://colorado-qc.odoo.com/web/assets/3d8db59/web.assets_web.min.js:7051:455)
    at new ComponentNode (https://colorado-qc.odoo.com/web/assets/3d8db59/web.assets_web.min.js:1002:202)
    at https://colorado-qc.odoo.com/web/assets/3d8db59/web.assets_web.min.js:1541:6
    at MrpDisplayAction.template (eval at compile (https://colorado-qc.odoo.com/web/assets/3d8db59/web.assets_web.min.js:1501:374), <anonymous>:19:12)
    at Fiber._render (https://colorado-qc.odoo.com/web/assets/3d8db59/web.assets_web.min.js:940:96)
    at Fiber.render (https://colorado-qc.odoo.com/web/assets/3d8db59/web.assets_web.min.js:939:6)
    at ComponentNode.initiateRender (https://colorado-qc.odoo.com/web/assets/3d8db59/web.assets_web.min.js:1007:47)

Caused by: TypeError: Cannot set properties of undefined (setting 'domain')
    at MrpDisplaySearchModel.setWorkcenterFilter (https://colorado-qc.odoo.com/web/assets/3d8db59/web.assets_web.min.js:23234:140)
    at MrpDisplaySearchModel._activateDefaultSearchItems (https://colorado-qc.odoo.com/web/assets/3d8db59/web.assets_web.min.js:23236:138)
    at MrpDisplaySearchModel.load (https://colorado-qc.odoo.com/web/assets/3d8db59/web.assets_web.min.js:6759:159)
    at async WithSearch.<anonymous> (https://colorado-qc.odoo.com/web/assets/3d8db59/web.assets_web.min.js:7052:1)
    when in install the shop floor how can i solve this problem
